name: Deploy to GCP

on:
  push:
    branches: [main]

env:
  PROJECT_DIR: /home/projects_vizuara_com/projects/visual-ml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy repo to GCP server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          source: "backend,frontend,README.md,docker-compose.yml"
          target: ${{ env.PROJECT_DIR }}
          overwrite: true

          